### ISSUE TITLE
Upgrade UI and Footer.

### ISSUE THREAD

**Issue by HemanthKR07** [RohanKumar01/donation-website#7]

**Comment by HemanthKR07** [comment]
Hey @RohanKumar01 ,
I can make this UI better and the Footer too,
Im working on this, please assign it to me.

**Comment by RohanKumar01** [comment]
Hey @HemanthKR07 
You can create a pull request with above said changes.

**Comment by HemanthKR07** [comment]
Hey @RohanKumar01 ,
Can I know why was my pr reverted ?
